### ISSUE TITLE
unable to use function MATCH in the requested context (code 1)

### ISSUE THREAD

**Issue by solome** [yahoo/squidb#45]
when use

```java
Query query = Query.select().where(Person.UUID.match("uuid"));
```

I get a err msg:

```bash
java.lang.RuntimeException: Unable to start activity ComponentInfo
... ...
Caused by: 
android.database.sqlite.SQLiteException: unable to use function MATCH in the requested context (code 1)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
            at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
            at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
            at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
            at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
            at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
            at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
            at android.database.CursorWrapper.moveToNext(CursorWrapper.java:166)
           
```

**Comment by jdkoren** [comment]
The `MATCH` function is for use with SQLite extensions. The Android SQLite binary supports the FTS3 and FTS4 extensions for Full Text Search; SquiDB provides equivalent support via the `VirtualTable` class and the `virtualModule` argument of the `@TableModelSpec` annotation.

For a normal table, `match()` is not the right function for comparing text. In the example you gave, I think you want to use `eq()` to find exactly that value in the column (the alternative is `like()`, which allows certain wildcards in the argument so you can match part of the value in the column). I refer you to the [SQLite documentation](https://www.sqlite.org/lang_expr.html#like) that describes these operators/functions in more detail.
