### ISSUE TITLE
Query without _id will cause error when list item touched

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#46]
I have this query
```
    private static Function<String> authorCase = Function.caseWhen(Author.MIDDLE_NAME.isEmpty(),
            Function.strConcat(Author.NAME, " ", Author.SURNAME),
            Function.strConcat(Author.NAME, " ", Author.MIDDLE_NAME, " ", Author.SURNAME));
    public static  Property.StringProperty AUTHOR = Property.StringProperty.fromFunction(Function.groupConcatDistinct(authorCase), "author");

    private static final Query ALL_BOOK_DETAILS_QUERY;
    static {
        Property.StringProperty category = Property.StringProperty.fromFunction(Function.groupConcatDistinct(Category.NAME), "category");

        ALL_BOOK_DETAILS_QUERY = Query.select(Book.TITLE, Book.ISBN, Book.EAN, Book.YEAR,
                Book.PAGES, Book.EDITION, AUTHOR)
                .from(Book.TABLE)
                .innerJoin(MixAuthorBook.TABLE, MixAuthorBook.FK_BOOK.eq(Book.ID))
                .innerJoin(Author.TABLE, Author.ID.eq(MixAuthorBook.FK_AUTHOR))
                .groupBy(Book.ID);
    }
```

and when the list is populated with results of this query I have following error when clicked on an item:

```
07-17 18:40:40.537  13428-13428/com.greladesign.android.exlibris E/InputEventReceiver﹕ Exception dispatching input event.
07-17 18:40:40.537  13428-13428/com.greladesign.android.exlibris E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
07-17 18:40:40.597  13428-13428/com.greladesign.android.exlibris E/MessageQueue-JNI﹕ java.lang.IllegalArgumentException: column '_id' does not exist
            at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:308)
            at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:82)
            at com.yahoo.squidb.data.SquidCursor$CursorReadingVisitor.columnIndex(SquidCursor.java:163)
            at com.yahoo.squidb.data.SquidCursor$CursorReadingVisitor.visitLong(SquidCursor.java:127)
            at com.yahoo.squidb.data.SquidCursor$CursorReadingVisitor.visitLong(SquidCursor.java:105)
            at com.yahoo.squidb.sql.Property$LongProperty.accept(Property.java:537)
            at com.yahoo.squidb.data.SquidCursor.get(SquidCursor.java:70)
            at com.yahoo.squidb.utility.SquidCursorAdapter.getItemId(SquidCursorAdapter.java:137)
            at android.widget.AdapterView.getItemIdAtPosition(AdapterView.java:768)
            at android.widget.AdapterView.setSelectedPositionInt(AdapterView.java:1154)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3650)
            at android.widget.ListView.onTouchEvent(ListView.java:4027)
            at android.view.View.dispatchTouchEvent(View.java:7198)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2181)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1916)
            at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6882)
            at android.widget.ListView.dispatchTouchEvent(ListView.java:4441)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2007)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1461)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2454)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1955)
            at android.view.View.dispatchPointerEvent(View.java:7392)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3577)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3506)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4620)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4599)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4695)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:200)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:131)
            at android.os.Looper.loop(Looper.java:132)
            at android.app.ActivityThread.main(ActivityThread.java:5520)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
07-17 18:40:40.607  13428-13428/com.greladesign.android.exlibris W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x410fc540)
07-17 18:40:40.617  13428-13428/com.greladesign.android.exlibris E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: column '_id' does not exist
            at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:308)
            at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:82)
            at com.yahoo.squidb.data.SquidCursor$CursorReadingVisitor.columnIndex(SquidCursor.java:163)
            at com.yahoo.squidb.data.SquidCursor$CursorReadingVisitor.visitLong(SquidCursor.java:127)
            at com.yahoo.squidb.data.SquidCursor$CursorReadingVisitor.visitLong(SquidCursor.java:105)
            at com.yahoo.squidb.sql.Property$LongProperty.accept(Property.java:537)
            at com.yahoo.squidb.data.SquidCursor.get(SquidCursor.java:70)
            at com.yahoo.squidb.utility.SquidCursorAdapter.getItemId(SquidCursorAdapter.java:137)
            at android.widget.AdapterView.getItemIdAtPosition(AdapterView.java:768)
            at android.widget.AdapterView.setSelectedPositionInt(AdapterView.java:1154)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3650)
            at android.widget.ListView.onTouchEvent(ListView.java:4027)
            at android.view.View.dispatchTouchEvent(View.java:7198)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2181)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1916)
            at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6882)
            at android.widget.ListView.dispatchTouchEvent(ListView.java:4441)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2187)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1930)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2007)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1461)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2454)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1955)
            at android.view.View.dispatchPointerEvent(View.java:7392)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3577)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3506)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4620)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4599)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4695)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:200)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:131)
            at android.os.Looper.loop(Looper.java:132)
            at android.app.ActivityThread.main(ActivityThread.java:5520)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
```

I have to add the _id to the selected columns to avoid this error

```
ALL_BOOK_DETAILS_QUERY = Query.select(Book.TITLE, Book.ISBN, Book.EAN, Book.YEAR,
```

**Comment by jdkoren** [comment]
Yes, that is by design. We mimic Android's `CursorAdapter`, so we need an ID column to implement `getItemId()`. I suppose you can override `getItemId()` and just return something like `0` or `position`, but it's probably easier (and better) to add `Book.ID` to your query.

**Comment by LukaszGrela** [comment]
Add this info to the WIKI please;)
